### ISSUE TITLE
check min_rtt value in collector/extra_data feed

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/piecewise#42]
For the purposes of checking the data feed values, check the values of min_rtt in the postgres table to confirm whether they have decimal places. If they do, confirm the values are not being truncated in the data feed.

**Comment by nkinkade** [comment]
The database only has integer values.  The values for min_rtt stored in the extra_data table are [cast to an integers](https://github.com/opentechinstitute/piecewise/blob/master/collector/collector/wsgi.py#L308) before insertion.  I think my reasoning for doing this was  a) to simplify form validation b) because RTT is measured in milliseconds and it isn't clear that small fractions of one millisecond are really useful for this purpose.

**Comment by critzo** [comment]
I think we should cast values for these metrics in postgres based on the format they are stored in within Big Query. Data consistency would be the reason. The aggregation and/or visualizations can reduce values to integers if that's what we want to display. 

I'm going to run a query now to see what min_rtt is stored in to confirm whether this issue can be closed.

**Comment by critzo** [comment]
minrtt is stored as an integer in Big Query. re-closing.
