### ISSUE TITLE
Aggregate by quarter instead of by month

### ISSUE THREAD

**Issue by georgiamoon** [opentechinstitute/piecewise#90]
I forget if we can do this already, but if not we should when we know we don't have as much data in certain locations -- change the time aggregations to quarters or years, etc, or remove the timeline and just show all the data we know about.

If this is possible, then let's document it?

**Comment by georgiamoon** [comment]
@dwins sent me this: https://www.postgresql.org/docs/9.6/static/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC

which means we could change the default to quarters! something to look at as part of the #mozsprint

**Comment by critzo** [comment]
This can be accomplished by changing the UI display from months to quarters and setting the query string to bin by quarter.

**Comment by critzo** [comment]
@georgiamoon @meagdoh I'm putting some notes here on what I've been working on for this issue. 

* I'm working on this in a feature branch: https://github.com/critzo/piecewise/tree/quarters
* A GCE VM is available to test deploy to here: https://104.197.237.109/
  * Georgia you should have ssh access to this VM now
  * Meag, if you send me your SSH public key, I'll add your access to it

**Summary of Work:**
* Postgres supports quarter aggregation out of the box, so changing the [dataURL](https://github.com/critzo/piecewise/blob/quarters/ansible/templates/index.html.j2#L294) is pretty easy.
* Debugging and getting the JavaScript / JQuery to update the URL with appropriate start and end timestamps when the user clicks on the timeline element has been the main sticky bit.
* Two things to-do:
  * Adjust the timeline/slider so it displays four quarters instead of 12 months
    * Month / Quarter labels are defined in the [global config file](https://github.com/critzo/piecewise/blob/quarters/ansible/group_vars/all/piecewise_global_config.yml#L196)
    * Slider instantiation is happening in `piecewise_web/mlab.js`
      * [L168](https://github.com/critzo/piecewise/blob/quarters/piecewise_web/js/mlab.js#L168)
      * [L198](https://github.com/critzo/piecewise/blob/quarters/piecewise_web/js/mlab.js#L198)
  * Adjust the functions that provide start/end when selecting a particular quarter
    * I started a function, [getQuarter](https://github.com/critzo/piecewise/blob/quarters/piecewise_web/js/mlab.js#L15), to provide the start/end timestamps of a quarter, given a selected month, but it's not working. 
    * I think that getQuarter needs to be called on the [index page](https://github.com/critzo/piecewise/blob/quarters/ansible/templates/index.html.j2#L341-L366), so that when users click on a selected tick mark the quarter values are updated.
